[package]
name = "x402-kit"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = { version = "0.4.3" }
alloy-primitives = { version = "1" }
bon = { version = "3" }
crypto-bigint = { version = "0.6", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = { version = "2" }
url = { version = "2" }
solana-sdk = { version = "3" }
chrono = { version = "0.4", default-features = false, features = ["std"] }
base64 = { version = "0.22" }
